version: '3.8'
services:
  postgres:
    image: "public.ecr.aws/docker/library/postgres:15.2-alpine"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demo_db
    ports:
      - "5559:5432"
